name: Compilation
on:
  push
jobs:
  linux:
    name: Compile on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libbsd-dev
      - name: Compile
        run: make || exit 1
      - name: Clean
        run: make fclean || exit 1
  macos:
    name: Compile on MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        uses: openrndr/setup-opengl@v1.1
        with:
          submodules: true
          fetch-depth: 0
      - name: Compile
        run: make || exit 1
      - name: Clean
        run: make fclean || exit 1
