name: Valgrind
on:
  push
jobs:
  valgrind:
    name: Run Valgrind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xdotool valgrind
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libbsd-dev
      - name: Compile
        run: make || exit 1
      - name: Run
        run: ./scripts/check_valgrind.sh ./maps/valid.rt
