name: Valgrind
on:
  push
jobs:
  valgrind:
    name: Run Valgrind
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xdotool valgrind
      - name: Run
        run: xvfb-run --auto-servernum ./scripts/check_valgrind.sh
