name: Valgrind
on:
  push
jobs:
  valgrind-valid:
    name: Run Valgrind Valid Map
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xdotool valgrind
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libbsd-dev
      - name: Compile
        run: make || exit 1
      - name: Run Valid Map
        run: xvfb-run --auto-servernum ./scripts/check_valgrind.sh ./maps/valgrind.rt 1.1
  valgrind-parsing:
    name: Run Valgrind Parsing Maps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb xdotool valgrind
          sudo apt install -y \
            libx11-dev \
            libxext-dev \
            libxrandr-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libbsd-dev
      - name: Compile
        run: make || exit 1
      - name: Run Parsing Maps
        run: xvfb-run --auto-servernum ./scripts/check_valgrind_parsing.sh
